# Generated by Django 5.1.7 on 2025-03-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='device_data',
            field=models.CharField(blank=True, help_text='Path to CSV file containing vital signs data', max_length=255, null=True),
        ),
    ]
