# Generated by Django 5.1.7 on 2025-03-23 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_issue_device_data'),
    ]

    operations = [
    ]
